# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-13 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ASV_Vessel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_ASV_Vessel', models.CharField(max_length=4)),
                ('Name', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('Mass', models.FloatField()),
                ('LCG', models.FloatField()),
                ('TCG', models.FloatField()),
                ('VCG', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Item', models.CharField(max_length=4)),
                ('ASV_Item', models.CharField(max_length=3)),
                ('Local_Group', models.IntegerField()),
                ('Global_Group', models.IntegerField()),
                ('Part_Name', models.CharField(max_length=32)),
                ('Description', models.TextField()),
                ('Mass', models.FloatField()),
                ('LCG', models.FloatField()),
                ('TCG', models.FloatField()),
                ('VCG', models.FloatField()),
            ],
        ),
    ]
