# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-15 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ASV_Vessel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_ASV_Vessel', models.CharField(max_length=4)),
                ('Name', models.CharField(max_length=200)),
                ('Description', models.TextField(blank=True)),
                ('Mass', models.FloatField(null=True)),
                ('LCG', models.FloatField(null=True)),
                ('TCG', models.FloatField(null=True)),
                ('VCG', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group_System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_GS', models.IntegerField(unique=True)),
                ('Mass', models.FloatField(blank=True, null=True)),
                ('LCG', models.FloatField(blank=True, null=True)),
                ('TCG', models.FloatField(blank=True, null=True)),
                ('VCG', models.FloatField(blank=True, null=True)),
                ('ID_ASV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weightsheet.ASV_Vessel')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Item', models.CharField(max_length=4)),
                ('ASV_Item', models.CharField(max_length=3)),
                ('Local_Group', models.IntegerField()),
                ('Global_Group', models.IntegerField()),
                ('Part_Name', models.CharField(max_length=32)),
                ('Description', models.TextField()),
                ('Quantity', models.FloatField()),
                ('Mass', models.FloatField()),
                ('LCG', models.FloatField()),
                ('TCG', models.FloatField()),
                ('VCG', models.FloatField()),
                ('ID_ASV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weightsheet.ASV_Vessel')),
                ('ID_GS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weightsheet.Group_System')),
            ],
        ),
    ]
