# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-15 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightsheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_system',
            name='ID_GS',
            field=models.IntegerField(),
        ),
    ]
