# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-15 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightsheet', '0002_auto_20171215_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bounding_Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X_aft', models.FloatField()),
                ('X_foward', models.FloatField()),
                ('Y_starboard', models.FloatField()),
                ('Y_portside', models.FloatField()),
                ('Z_bottom', models.FloatField()),
                ('Z_up', models.FloatField()),
            ],
        ),
    ]
