# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-15 22:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightsheet', '0003_bounding_box'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bounding_box',
            old_name='X_foward',
            new_name='X_forward',
        ),
    ]
