# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-20 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightsheet', '0004_auto_20171215_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asv_vessel',
            old_name='ID_ASV_Vessel',
            new_name='ASV_Project_Number',
        ),
    ]
