# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-31 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weightsheet', '0006_auto_20171228_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='asv_vessel',
            name='Create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='asv_vessel',
            name='Modified_data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
