# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-31 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightsheet', '0007_auto_20171231_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asv_vessel',
            old_name='Modified_data',
            new_name='Modified_date',
        ),
    ]
