# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-31 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weightsheet', '0008_auto_20171231_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asv_vessel',
            old_name='Create_date',
            new_name='Creation_date',
        ),
        migrations.RenameField(
            model_name='asv_vessel',
            old_name='Modified_date',
            new_name='Modification_date',
        ),
    ]
