# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-31 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightsheet', '0009_auto_20171231_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_system',
            name='LCG',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='group_system',
            name='Mass',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='group_system',
            name='TCG',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='group_system',
            name='VCG',
            field=models.FloatField(default=0),
        ),
    ]
