# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-06 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightsheet', '0019_auto_20180106_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asv_vessel',
            name='Name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='asv_vessel',
            unique_together=set([]),
        ),
    ]
